# Site settings
title: Blog of Hetu Ashara
name: Blog of Hetu Ashara
email: ashara.hetu@gmail.com
description: A personal blog of Hetu Ashara.
baseurl: "http://hetus.net" # the subpath of your site, e.g. /blog/
url: "http://hetus.net" # the base hostname & protocol for your site
twitter_username: hetuashara
github_username:  hetuashara
paginate: 20
# Build settings
markdown: kramdown
permalink : /:year/:month/:day/:categories/:title
