# Site settings
title: Blog of Hetu Ashara
name: Blog of Hetu Ashara
email: ashara.hetu@gmail.com
description: A personal blog of Hetu Ashara.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hetus.net" # the base hostname & protocol for your site
twitter_username: hetuashara
github_username:  hetuashara
paginate: 20
author: "Hetu Ashara"

# Build settings
markdown: kramdown
permalink : /:year/:month/:day/:categories/:title
analytics: UA-59777951-1