# Site settings
title: Blog of Hetu Ashara
name: Blog of Hetu Ashara
email: hetus.net@gmail.com
description: A personal blog of Hetu Ashara. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hetus.net" #the base hostname & protocol for your site
twitter_username: hetuashara
github_username:  hetuashara
paginate: 15
author: "Hetu Ashara"

# Build settings
markdown: kramdown
permalink : /:year/:month/:day/:categories/:title
