# Site settings
title: hetu-blog
email: your-email@domain.com
description: A personal blog of Hetu Ashara.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: hetuashara
github_username:  jekyll
paginate: 20
# Build settings
markdown: kramdown
permalink : /:year/:month/:day/:categories/:title
